# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-22 05:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='last_download_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
